app/routes/client_routes.py
from flask import Blueprint, render_template, session, flash, redirect, request, url_for
from ..models.models import Client, UserType, CommandeClient, CarteFidelite, LigneCommandeClient, Article, Categorie, SousCategorie, SousSousCategorie, Panier, ModePaiement, LignePanier, ModeLivraison, StatutCommande, Filiale
from flask_login import LoginManager, login_user, current_user, login_required, logout_user, UserMixin
import json
from app import db
client_bp = Blueprint('client', __name__, url_prefix="/client")


@client_bp.route('/dashboard')
def client_dashboard():
    user_type = session.get('user_type', None)
    return render_template('dashboard.html', user_type='client')

@client_bp.route('/client')
def client():
    user_type = session.get('user_type', None)
    all_clients = Client.query.all()
    return render_template('clients.html', clients=all_clients, user_type='client')

@client_bp.route('/client/<int:client_id>', methods=['GET'])
def client_profile(client_id):
    if session.get('user_type') != 'client':
        flash("Accès non autorisé", 'danger')
        return redirect(url_for('auth.login'))
    user_id = session.get('user_id')
    client = Client.query.get_or_404(user_id)
    commandesclient = CommandeClient.query.filter_by(client_id=client.id_client).all()
    return render_template('client/client_profile.html', user_type='client', client=client, commandesclient=commandesclient)#, user=client)

@client_bp.route('/list')
def client_list():
    all_clients = Client.query.all()
    return render_template('client/list_client.html', clients=all_clients)

@client_bp.route("/add/<id_article>", methods=['POST', 'GET'])
def ajouter_au_panier(id_article):
    if not current_user.is_authenticated:
        flash('You must login first! Login now!','error')
        return redirect(url_for('auth.login'))
    panier = Panier.query.filter_by(id_client=current_user.id_client).first()
    if not panier:
        panier = Panier(client=current_user)
        db.session.add(panier)
        db.session.flush()
    article = Article.query.get_or_404(id_article)

    quantite_str = request.form.get('quantite')
    if quantite_str and quantite_str.isdigit():
        quantite = int(quantite_str)
        panier.ajouter_article(article, quantite)
    else :
        delta_str = request.form.get('delta')
        if not delta_str or not delta_str.lstrip('-').isdigit():
            flash('modification de quantite invalide', 'error')
            return redirect(url_for(client.afficher_panier))
        delta=int(delta_str)
        actuel_qte = panier.quantite_article(article)
        nouvelle_qte = actuel_qte + delta
        panier.ajouter_article(article, nouvelle_qte)
        flash(f'{delta} x {article.nom_article} modifié dans le panier', 'success')
    db.session.commit()
    from_panier = request.form.get('from_panier', False)
    if from_panier == 'true':
        return redirect(url_for('client.afficher_panier'))
    else:
        return redirect(url_for('client.afficher_panier'))

@client_bp.route("/remove/<id_article>/<quantite>") 
def remove(id_article, quantite):
    if not current_user.is_authenticated:
        flash('You must login first! Login now!','error')
        return redirect(url_for('auth.login'))
    panier = Panier.query.filter_by(id_client=current_user.id_client).first()
    if not panier:
        flash('Aucun panier trouvé', 'error')
        return redirect(url_for('client.afficher_panier'))
    article = Article.query.get_or_404(id_article)
    panier.enlever_article(article, int(quantite))
    db.session.commit()
    flash('Article retiré du panier', 'success')
    return redirect(url_for('client.afficher_panier'))

@client_bp.route('/item/<int:id_article>')
def item(id_article):
	item = Article.query.get(id_article)
	return render_template('home/article_detail.html', item=item)

@client_bp.route("/panier")
@login_required
def afficher_panier():
    client = current_user
    modes_paiement = ModePaiement.query.all()
    modes_livraison = ModeLivraison.query.all()
    filiales = Filiale.query.all()
    if not modes_paiement:
        flash("Veuillez sélectionner un mode de paiement", "danger")
        return redirect(url_for('client.afficher_panier'))
    if not filiales:
        flash("Veuillez sélectionner une filiale", "danger")
        return redirect(url_for('client.afficher_panier'))
    panier = Panier.query.filter_by(id_client=current_user.id_client).first()
    if panier is None:
        lignes =[]
    else:
        db.session.refresh(panier)
        lignes = panier.lignes_panier.all()
        print(f"Lignes panier: {lignes}")
    prix = 0
    articles = []
    quantite = []
    price_ids = []
    for ligne in lignes:
        articles.append(ligne.article)
        quantite.append(ligne.quantite)
        #price_id_dict = {
		#	"prix_unitaire": ligne.article.prix_unitaire,
		#	"quantite": ligne.quantite,
		#	}
        price_ids.append({
            "prix_unitaire": ligne.article.prix_unitaire,
            "quantite" : ligne.quantite
        })
    articles_with_qty = list(zip(articles, quantite))
    prix = panier.montant_panier
    print(f"Lignes panier: {lignes}")
    return render_template('client/panier.html', client=client, articles=articles, prix=prix, price_ids=price_ids, quantite=quantite, articles_with_qty=articles_with_qty, modes_paiement=modes_paiement, modes_livraison=modes_livraison, filiales=filiales)


@client_bp.route('/valider_panier', methods=['POST', 'GET'])
@login_required
def valider_paiement():
    client = current_user
    panier = client.panier
    prix = panier.montant_panier
    statut_confirme = StatutCommande.query.filter_by(libel='Commande créée').first()
    if not statut_confirme:
        flash("le statut de la commande est introuvable", 'error')
        return redirect(url_for('client.afficher_panier'))
    modes_livraison = ModeLivraison.query.all()
    modes_paiement = ModePaiement.query.all()
    filiale_id_str = request.form.get('filiale_id', '').strip()
    if not filiale_id_str:
        flash('Veuillez sélectionner une filiale', 'warning')
        return redirect(url_for('client.afficher_panier'))
    try:
        filiale_id = int(filiale_id_str)
    except ValueError:
        flash('ID de filiale invalide', 'danger')
        return redirect(url_for('client.afficher_panier'))
    filiale = Filiale.query.get(filiale_id)
    if not filiale:
        flash('filiale introuvable', 'danger')
        return redirect(url_for('client.afficher_panier'))
    if request.method=='POST':
        mode_paiement_str = request.form.get('mode_paiement', '').strip()
        if not mode_paiement_str:
            flash("Veuillez sélectionner un mode de paiement", 'warning')
            return redirect(url_for('client.afficher_panier'))
        try:
            mode_id = int(mode_paiement_str)
        except ValueError:
            flash("Mode de paiement invalide", 'danger')
            return redirect(url_for('client.afficher_panier'))
        mode = ModePaiement.query.get(mode_id)
        if not mode:
            flash("Mode de paiement non trouvé", 'danger')
            return redirect(url_for('client.afficher_panier'))
        if mode.libel.lower() == 'compte_kaufmann':
            if panier.montant_panier > client.montant_initial:
                flash("Solde insuffisant", 'danger')
                return redirect(url_for('afficher_panier'))
            client.montant_initial -= panier.montant_panier
        
        print("Lignes panier au moment de générer commande:", panier.lignes_panier.all())
        commande = panier.generer_commande(statut=statut_confirme, mode_paiement=mode, filiale=filiale)
        for ligne in panier.lignes_panier.all():
            db.session.delete(ligne)
        db.session.flush()
        db.session.refresh(panier)
        print("Après commit, lignes panier:", panier.lignes_panier.all())
        db.session.commit()
        print("Après commit, lignes panier:", panier.lignes_panier.all())
        flash("Commande validée ‘", 'success')
        #return render_template('client/valider_panier.html', id_commande_client=commande.id_commande_client, 
        #                       modes_paiement=modes_paiement, modes_livraison=modes_livraison, prix=prix)
        return render_template('client/confirmation_commande.html', commande=commande)
    return redirect(url_for('client.afficher_panier'))
@client_bp.route('/confirmation_commande/<int:id_commande>')
@login_required
def confirmation_commande(id_commande):
    commande = CommandeClient.query.get_or_404(id_commande)
    return render_template('client/confirmation_commande.html', commande=commande)

app/routes/home_routes.py
from flask import Flask, Blueprint, request, render_template, redirect, session, url_for, flash
from app.models.models import Article, Categorie, SousCategorie, SousSousCategorie, Marque, Garantie, LigneCommandeClient, CommandeClient, Tag
from app import db
from sqlalchemy import inspect, func
from datetime import datetime
import json
home_bp = Blueprint('home', __name__)

@home_bp.route('/')
def index():
    return render_template('home.html')

@home_bp.route('/categories')
def categories():
    id_categorie = request.args.get('id_categorie', type=int)
    id_sous_categorie = request.args.get('id_sous_categorie', type=int)

    all_categories = Categorie.query.all()
    sous_categories = SousCategorie.query.filter_by(id_categorie=id_categorie).all() if id_categorie else []
    sous_sous_categories = SousSousCategorie.query.filter_by(id_sous_categorie=id_sous_categorie).all() if id_sous_categorie else []

    return render_template(
        'categorie.html',
        categories=all_categories,
        sous_categories=sous_categories,
        sous_sous_categories=sous_sous_categories,
        selected_categorie=id_categorie,
        selected_sous_categorie=id_sous_categorie
    )

@home_bp.route('/articles', methods=['GET', 'POST'])
def articles(): 
    selected_categorie = request.args.get('libel_categorie')
    selected_marque = request.args.get('libel_marque')
    min_price = request.args.get('min_price', type=float)
    max_price = request.args.get('max_price', type=float)
    tag_string = []
    if request.method == 'POST':
        raw_tags = request.form.get("tags")
        if raw_tags:
            tag_string = json.loads(raw_tags)
            print("tags recus :", tag_string)
        for tag in tag_string:
            libel = tag['libel']
            color = tag['color']
            print(f"tag : {libel}, couleur : {color}")


    query = Article.query

    if selected_categorie:
        query = query.join(Categorie).filter(Categorie.libel_categorie == selected_categorie)
    if selected_marque:
        query = query.join(Marque).filter(Marque.libel_marque == selected_marque)
    if min_price is not None:
        query = query.filter(Article.prix_unitaire >= min_price)
    if max_price is not None:
        query = query.filter(Article.prix_unitaire <= max_price)

    articles = query.all()
    categories = Categorie.query.all()
    marques = Marque.query.all()
    class DummyCommandes:
        commande_id = 1
    commande = DummyCommandes()
    return render_template('articles.html', articles=articles, commande=commande, categories=categories, marques=marques, tag_string=tag_string)

@home_bp.route('/article/<int:id_article>', methods=['GET', 'POST'])
def article_detail(id_article):
    article = Article.query.get_or_404(id_article)
    reference_date = request.args.get('reference_date')
    #tag_string = []

    #if request.method == 'POST':
    #    raw_tags = request.form.get("tags")
    #    print("Contenu brut des tags :", raw_tags)
    #    print("Requête POST reçue")
    #    if raw_tags:
    #        try:
    #            print('tags recus:', tag_string)
    ##            tag_string = json.loads(raw_tags)
    #            if isinstance(tag_string, list):
    #                Tag.query.filter_by(id_article=id_article).delete()
    ##                db.session.commit()
    #                for tag in tag_string:
    #                    libel = tag['libel']
    #                    color = tag['color']
    #                    new_tag = Tag(id_article=id_article, libel=libel, color=color)
    #                    db.session.add(new_tag)
    #                db.session.commit()
    #                print("Tags mis à jour.")
    #            else:
    #                print("Format invalide : les tags ne sont pas une liste.")
    #        except Exception as e:
    #            print("Erreur JSON :", e)
    #tags_en_base = Tag.query.filter_by(id_article=id_article).all()
    #tag_string = [{'libel':t.libel, 'color':t.color} for t in tags_en_base]
    if request.method == 'POST':
        # Les tags envoyés dans un champ caché JSON string
        tags_json = request.form.get('tags')
        if tags_json:
            try:
                tags_list = json.loads(tags_json)
            except Exception as e:
                flash("Erreur lors du traitement des tags.", "danger")
                return redirect(url_for('home.article_detail', id_article=id_article))

            # id_category_default à adapter selon ta logique (exemple 1)
            id_category_default = 1

            # Synchronise les tags de l'article avec ceux reçus
            Tag.add_tags_to_entity(article, tags_list, id_category_default)
            flash("Tags mis à jour avec succès.", "success")
            return redirect(url_for('home.article_detail', id_article=id_article))

    # Pour le GET, on prépare la variable tag_string pour le JS
    # Convertir les tags SQLAlchemy en liste de dicts
    tag_string = [
        {'libel': tag.libel, 'color': tag.color} for tag in article.tags
    ]
    ventes_sorties = db.session.query(
        func.coalesce(func.sum(LigneCommandeClient.quantite),0)).join(CommandeClient).filter(LigneCommandeClient.id_article == id_article)

    if reference_date:
        reference_date = datetime.strptime(reference_date, '%Y-%m-%d').date()
        ventes_sorties = ventes_sorties.filter(CommandeClient.date <= reference_date)

    vente_sorties_total = ventes_sorties.scalar() or 0
    return render_template(
        'article_detail.html',
        article=article,
        reference_date=reference_date,
        vente_sorties_total=vente_sorties_total, tag_string=tag_string)
    


        

app/templates/client/client_profile.html
{% extends "base.html" %}
{% block content %}
  <h2>{{ client.nom }}</h2>
  <div class="container">
    <div class="display-6" style="background-color: whitesmoke;">
      <h3>Informations sur : <strong>{{ client.nom }} {{ client.prenom }}</strong></h3>
      <p>User type est : {{ user_type }} - {{ user_id }}</p>
    </div> 
    <div class="row"> 
    <div class="col"><strong>ID</strong></div>
    <div class="col"><strong>Nom</strong></div> 
    <div class="col"><strong>Prenom</strong></div> 
    <div class="col"><strong>Adresse</strong></div>
    <div class="col"><strong>Code Postal</strong></div> 
    <div class="col"><strong>Commune</strong></div>
    <div class="col"><strong>Canton</strong></div> 
    <div class="col"><strong>Telephone</strong></div>
    <div class="col"><strong>EMail</strong></div>
  </div>
  <div class="row"> 
    <div class="col">{{ client.id_client }}</div>
    <div class="col">{{ client.nom }}</div>
    <div class="col">{{ client.prenom }}</div> 
    <div class="col">{{ client.adresse }} {{ client.numero }}</div> 
    <div class="col">{{ client.code_postal }}</div>
    <div class="col">{{ client.commune }}</div> 
    <div class="col">{{ client.canton }}</div> 
    <div class="col">{{ client.telephone }}</div>
    <div class="col">{{ client.montant_initial }}</div>
  </div>
</div>
<div class="container">


</div>
<div class="container">
  <h2>Commandes</h2>
  {% if commandesclient %}
  {% for cmd in commandesclient %}
  <div class="accordion" id="heading{{ cmd.id_commande_client }}">
    <div class="accordion-item">
      <h2 class="accordion-header">
        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapse{{ cmd.id_commande_client }}" aria-expanded="true" aria-controls="collapse{{ cmd.id_commande_client }}">
          Commande {{ cmd.id_commande }} le {{ cmd.date.strftime('%d/%m/%Y') }}
        </button>
      </h2>
      <div id="collapse{{ cmd.id_commande_client }}"class="accordion-collpase collapse-show" aria-labelledby="heading{{ cmd.id_commande_client }}" data-bs-parent="#commandes">
        <div class="accordion-body">
          <table class="table table-striped">
            <thead>
              <tr>
                <th>Nom d'article</th>
                <th>Quantite</th>
                <th>Prix</th>
              </tr>
            </thead>
            <tbody>
              {% for item in cmd.articles_choisis %}
              <tr>
                <td>{{ item.articles_commandes_client.nom_article }}</td>
                <td>{{ item.quantite }}</td>
                <td>{{ item.articles_commandes_client.prix_unitaire }}</td>
              </tr>
              {% endfor %}
            </tbody>
            <tfoot>
              <tr class="table-info">
                <td colspan="2"><strong>Total de la commande</strong></td>
                <td><strong>{{ cmd.montant_total }}</strong></td>
              </tr>
            </tfoot>
          </table>
        </div>
      </div>  
    </div>
  </div>
  {% endfor %}
  {% endif %}
</div>
{% endblock %}

app/templates/client/clients.html
{% extends "base.html" %}
{% block content %}
<div style="margin-left:50px;"> 
<h2>Liste des clients</h2>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Id</th>
      <th scope="col">Name</th>
    </tr>
  </thead>
  <tbody>
    {% for client in clients %}
    <tr>
      <td><a href="#"><!-- url_for('client_profile', client_id=client.id_client) ## --> {{ client.id_client }}</a></td>
      <td><strong>{{ client.nom }}</strong> {{ client.prenom }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
    
      <li></li>
    
    </div>
{% endblock %}

app/templates/client/list_client.html
{% extends 'base.html' %}
{% block content %}
<div style="margin-left:50px;"> 
<h2>Liste des clients</h2>
<p>{{ user_type }} - {{ user_id }}</p>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Id</th>
      <th scope="col">Name</th>
      <th scope="col">Prénom</th>
    </tr>
  </thead>
  <tbody>
    {% for client in clients %}
    <tr>
      <td><a href="{{ url_for('client.client_profile', client_id=client.id_client) }}">{{ client.id_client }}</a></td>
      <td><strong>{{ client.nom }}</strong></td>
      <td><strong>{{ client.prenom }}</strong></td>
    </tr>
    {% endfor %}
  </tbody>
</table>
      <li></li>
    </div>
{% endblock %}

app/templates/client/panier.html
{% extends 'base.html' %}
{% block content %}
<div class="container py-5">
    <h1 class="mb-5">Your Shopping Cart</h1>
    <div class="row">
        <div class="col-lg-8">
            <!-- Cart Items -->
            <div class="card mb-4">
                <div class="card-body">
                    {% if articles_with_qty %}
                        {% for article, qte in articles_with_qty %}
                        <div class="row cart-item mb-3">
                            <div class="col-md-3">
                                <img src="#" alt="{{ article.nom_article}}" class="img-fluid rounded">
                            </div>
                            <div class="col-md-5">
                                <h5 class="card-title">{{ article.nom_article}}</h5>
                            </div>
                            <div class="col-md-2">
                                <form method="POST" action="{{ url_for('client.ajouter_au_panier', id_article=article.id_article) }}">
                                    <input type="hidden" name="from_panier" value="true">
                                    <div class="input-group">
                                        <button class="btn btn-outline-secondary btn-sm" type="submit" name="delta" value="-1" {% if qte <=1 %}disabled{% endif %}>-</button>
                                        <input style="max-width:100px" type="text" class="form-control  form-control-sm text-center"
                                            value="{{ qte }}" readonly>
                                        <button class="btn btn-outline-secondary btn-sm" type="submit" name="delta" value="1">+</button>
                                    </div>
                                </form>
                            </div>
                            <div class="col-md-2 text-end">
                                <p class="fw-bold">{{ '{:.2f}'.format(article.prix_unitaire * qte) }} CHF</p>
                                <a href="{{ url_for('client.remove', id_article=article.id_article, quantite=qte) }}" class="btn btn-sm btn-outline-danger" title="Supprimer">
                                    <i class="bi bi-trash"></i>
                                </a>
                            </div>
                        </div>
                        {% endfor %}
                    {% else %}
                    <p class="text-center text-muted">Votre panier est vide</p>    
                    {% endif %}
                <hr>
                </div>
            </div>
            <!-- Continue Shopping Button -->
            <div class="text-start mb-4">
                <a href="{{ url_for('home.articles') }}" class="btn btn-outline-primary">
                    <i class="bi bi-arrow-left me-2"></i>Continuer vos achats
                </a>
            </div>
        </div>
        <div class="col-lg-4">
            <!-- Cart Summary -->
            <div class="card cart-summary">
                <div class="card-body">
                    <h5 class="card-title mb-4">Résumé de la commande</h5>
                    <div class="d-flex justify-content-between mb-3">
                        <span>Sous-total</span>
                        <span>{{ '{:.2f}' .format(prix) }} CHF</span>
                    </div>
                    <div class="d-flex justify-content-between mb-3">
                        <span>Frais de livraison</span>
                        <span>10.00 CHF </span>
                    </div>
                    <div class="d-flex justify-content-between mb-3">
                        <span>Tax</span>
                        <span>{{ '{:.2f}' .format(prix * 0.081) }} CHF</span>
                    </div>
                    <hr>
                    <div class="d-flex justify-content-between mb-4">
                        <strong>Total</strong>
                        <strong>{{ '{:.2f}' .format(prix + 10.00) }} CHF</strong>
                    </div>
                    <form method="POST" action="{{ url_for('client.valider_paiement') }}">
                        <input type="hidden" value="{{ prix }}" name="montant_total">
                        <div class="mb-3">
                            <p>Choissisez une filiale</p>
                            <select class="form-select mb-3" name="filiale_id" required>
                                <option value=" ">---sélectionnier</option>
                                {% for filiale in filiales %}
                                <option value="{{ filiale.id_filiale }}">{{ filiale.nom }}</option>
                                {% endfor %}
                            </select>
                            <p>Choissisez un mode de livraison</p>
                            <select class="form-select mb-3" name="mode_livraison" required>
                                <option value=" ">---sélectionnier</option>
                                {% for mode in modes_livraison %}
                                <option value="{{ mode.id_mode_livraison }}">{{mode.libel }}</option>
                                {% endfor %}
                            </select>
                            <p>Choissisez un mode de paiement:</p>
                            <select class="form-select mb-3" name="mode_paiement" required>
                                {% for mode in modes_paiement %}
                                <option value="{{ mode.id_mode_paiement }}">{{mode.libel }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <button type="submit" class="btn btn-success w-100">
                            Conclure la commande
                        </button>
                    </form>
                </div>
            </div>
            <!-- Promo Code -->
            <div class="card mt-4">
                <div class="card-body">
                    <h5 class="card-title mb-3">Apply Promo Code</h5>
                    <div class="input-group mb-3">
                        <input type="text" class="form-control" placeholder="Enter promo code">
                        <button class="btn btn-outline-secondary" type="button">Apply</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/client/valider_panier.html
{% extends 'base.html' %}
{% block content %}
<div class="container py-5">
    <h1 class="mb-5">Your Shopping Cart</h1>
    <div class="row">
        <div class="col-lg-8">
            <!-- Cart Items -->
            <div class="card mb-4">
                <div class="card-body">
                    {% if articles_with_qty %}
                    {% for article, qte in articles_with_qty %}
                    <div class="row cart-item mb-3">
                        <div class="col-md-3">
                            <img src="#" alt="{{ article.nom_article}}" class="img-fluid rounded">
                        </div>
                        <div class="col-md-5">
                            <h5 class="card-title">{{ article.nom_article}}</h5>
                        </div>
                        <div class="col-md-2">
                            <form method="POST"
                                action="{{ url_for('client.ajouter_au_panier', id_article=article.id_article) }}">
                                <input type="hidden" name="from_panier" value="true">
                                <div class="input-group">
                                    <button class="btn btn-outline-secondary btn-sm" type="submit" name="delta"
                                        value="-1" {% if qte <=1 %}disabled{% endif %}>-</button>
                                    <input style="max-width:100px" type="text"
                                        class="form-control  form-control-sm text-center" value="{{ qte }}" readonly>
                                    <button class="btn btn-outline-secondary btn-sm" type="submit" name="delta"
                                        value="1">+</button>
                                </div>
                            </form>
                        </div>
                        <div class="col-md-2 text-end">
                            <p class="fw-bold">{{ '{:.2f}'.format(article.prix_unitaire * qte) }} CHF</p>
                            <a href="{{ url_for('client.remove', id_article=article.id_article, quantite=qte) }}"
                                class="btn btn-sm btn-outline-danger" title="Supprimer">
                                <i class="bi bi-trash"></i>
                            </a>
                        </div>
                    </div>
                    {% endfor %}
                    {% else %}
                    <p class="text-center text-muted">Votre panier est vide</p>
                    {% endif %}
                    <hr>
                </div>
            </div>
            <!-- Continue Shopping Button -->
            <div class="text-start mb-4">
                <a href="{{ url_for('home.articles') }}" class="btn btn-outline-primary">
                    <i class="bi bi-arrow-left me-2"></i>Continuer vos achats
                </a>
            </div>
        </div>
        <div class="col-lg-4">
            <!-- Cart Summary -->
            <div class="card cart-summary">
                <div class="card-body">
                    <h5 class="card-title mb-4">Résumé de la commande</h5>
                    <div class="d-flex justify-content-between mb-3">
                        <span>Sous-total</span>
                        <span>{{ '{:.2f}' .format(prix) }} CHF</span>
                    </div>
                    <div class="d-flex justify-content-between mb-3">
                        <span>Frais de livraison</span>
                        <span>10.00 CHF </span>
                    </div>
                    <div class="d-flex justify-content-between mb-3">
                        <span>Tax</span>
                        <span>{{ '{:.2f}' .format(prix * 0.081) }} CHF</span>
                    </div>
                    <hr>
                    <div class="d-flex justify-content-between mb-4">
                        <strong>Total</strong>
                        <strong>{{ '{:.2f}' .format(prix + 10.00) }} CHF</strong>
                    </div>
                    
                </div>
            </div>
            <!-- Promo Code -->
            <div class="card mt-4">
                <div class="card-body">
                    <h5 class="card-title mb-3">Apply Promo Code</h5>
                    <div class="input-group mb-3">
                        <input type="text" class="form-control" placeholder="Enter promo code">
                        <button class="btn btn-outline-secondary" type="button">Apply</button>
                    </div>
                </div>
            </div>
            <div class="card mt-4 d-none" id="validation-section">
                <div class="card-body">
                    <h5 class="card-title mb-4">valider la commande</h5>
                    <form method="POST" action="{{ url_for('client.valider_paiement' ) }}">
                        <p>Choissisez une filiale</p>
                        <select class="form-select mb-3" name="filiale_id" required>
                            <option value=" ">---sélectionnier</option>
                            {% for filiale in filiales %}
                            <option value="{{ filiale.id_filiale }}">{{filiale.nom }}</option>
                            {% endfor %}
                        </select>
                        <p>Choissisez un mode de livraison</p>
                        <select class="form-select mb-3" name="mode_livraison" required>
                            <option value=" ">---sélectionnier</option>
                            {% for mode in modes_livraison %}
                            <option value="{{ mode.id_mode_livraison }}">{{mode.libel }}</option>
                            {% endfor %}
                        </select>
                        <p>Choissisez un mode de paiement:</p>
                        <select class="form-select mb-3" name="mode_paiement" required>
                            {% for mode in modes_paiement %}
                            <option value="{{ mode.id_mode_paiement }}">{{mode.libel }}</option>
                            {% endfor %}
                        </select>
                        <input type="hidden" name="montant_total" value="{{ prix }}">
                        <button type="submit" class="btn btn-primary w-100">Valider le paiement</button>
                    </form>
            
                </div>  
            </div>

        </div>
    </div>
</div>  
{% endblock %}